# Generated by Django 5.0.2 on 2026-02-12 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_state', models.JSONField()),
                ('current_turn', models.CharField(default='r', max_length=1)),
                ('status', models.CharField(default='ongoing', max_length=20)),
                ('player_side', models.CharField(default='r', max_length=1)),
                ('ai_side', models.CharField(default='b', max_length=1)),
                ('difficulty', models.CharField(default='normal', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.IntegerField(help_text='Move number (half-move)')),
                ('side', models.CharField(max_length=1)),
                ('from_row', models.IntegerField()),
                ('from_col', models.IntegerField()),
                ('to_row', models.IntegerField()),
                ('to_col', models.IntegerField()),
                ('piece', models.CharField(max_length=5)),
                ('captured', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
            ],
            options={
                'ordering': ['ply'],
            },
        ),
    ]
