# Generated by Django 5.0.2 on 2026-04-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_add_ai_thinking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ai_side',
            field=models.CharField(blank=True, default='b', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('player_red', models.CharField(blank=True, max_length=255, null=True)),
                ('player_black', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_session', to='games.game')),
            ],
        ),
    ]
